### ISSUE TITLE
Bootloop

### ISSUE THREAD

**Issue by gerobaktekno** [WolfAURman/ota_update#2]
Thank you for your dedication for this rom,

But, everytime i flash the rom, it's cause bootloop on my device. 

Do you have recomendation for installation method or suggested recovery to use to install?

Thank you

**Comment by WolfAURman** [comment]
> Thank you for your dedication for this rom,
> 
> But, everytime i flash the rom, it's cause bootloop on my device.
> 
> Do you have recomendation for installation method or suggested recovery to use to install?
> 
> Thank you

Visit my telegram channel and use the instructions you need https://t.me/WolfAURmanRedmi9Builds

**Comment by gerobaktekno** [comment]
Well noted, thank you
